#include<stdio.h>
#include<stdlib.h>

int main()
{
    printf("I will not plagiarize in programming assignments and exams, nor will I directly copy and paste code generated by large language models.\n");
    return 0;
}
